// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: notification/v1/notification.proto

// 1. Tambahkan suffix versi (.v1) sesuai aturan Buf

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_SendVerificationEmail_FullMethodName  = "/notification.v1.NotificationService/SendVerificationEmail"
	NotificationService_SendInvitationEmail_FullMethodName    = "/notification.v1.NotificationService/SendInvitationEmail"
	NotificationService_SendPasswordResetEmail_FullMethodName = "/notification.v1.NotificationService/SendPasswordResetEmail"
	NotificationService_ScheduleTaskReminder_FullMethodName   = "/notification.v1.NotificationService/ScheduleTaskReminder"
	NotificationService_CancelTaskReminder_FullMethodName     = "/notification.v1.NotificationService/CancelTaskReminder"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SendVerificationEmail(ctx context.Context, in *SendVerificationEmailRequest, opts ...grpc.CallOption) (*SendVerificationEmailResponse, error)
	SendInvitationEmail(ctx context.Context, in *SendInvitationEmailRequest, opts ...grpc.CallOption) (*SendInvitationEmailResponse, error)
	SendPasswordResetEmail(ctx context.Context, in *SendPasswordResetEmailRequest, opts ...grpc.CallOption) (*SendPasswordResetEmailResponse, error)
	ScheduleTaskReminder(ctx context.Context, in *ScheduleTaskReminderRequest, opts ...grpc.CallOption) (*ScheduleTaskReminderResponse, error)
	CancelTaskReminder(ctx context.Context, in *CancelTaskReminderRequest, opts ...grpc.CallOption) (*CancelTaskReminderResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendVerificationEmail(ctx context.Context, in *SendVerificationEmailRequest, opts ...grpc.CallOption) (*SendVerificationEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendVerificationEmailResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendVerificationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendInvitationEmail(ctx context.Context, in *SendInvitationEmailRequest, opts ...grpc.CallOption) (*SendInvitationEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendInvitationEmailResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendInvitationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendPasswordResetEmail(ctx context.Context, in *SendPasswordResetEmailRequest, opts ...grpc.CallOption) (*SendPasswordResetEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPasswordResetEmailResponse)
	err := c.cc.Invoke(ctx, NotificationService_SendPasswordResetEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) ScheduleTaskReminder(ctx context.Context, in *ScheduleTaskReminderRequest, opts ...grpc.CallOption) (*ScheduleTaskReminderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleTaskReminderResponse)
	err := c.cc.Invoke(ctx, NotificationService_ScheduleTaskReminder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CancelTaskReminder(ctx context.Context, in *CancelTaskReminderRequest, opts ...grpc.CallOption) (*CancelTaskReminderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskReminderResponse)
	err := c.cc.Invoke(ctx, NotificationService_CancelTaskReminder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	SendVerificationEmail(context.Context, *SendVerificationEmailRequest) (*SendVerificationEmailResponse, error)
	SendInvitationEmail(context.Context, *SendInvitationEmailRequest) (*SendInvitationEmailResponse, error)
	SendPasswordResetEmail(context.Context, *SendPasswordResetEmailRequest) (*SendPasswordResetEmailResponse, error)
	ScheduleTaskReminder(context.Context, *ScheduleTaskReminderRequest) (*ScheduleTaskReminderResponse, error)
	CancelTaskReminder(context.Context, *CancelTaskReminderRequest) (*CancelTaskReminderResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) SendVerificationEmail(context.Context, *SendVerificationEmailRequest) (*SendVerificationEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVerificationEmail not implemented")
}
func (UnimplementedNotificationServiceServer) SendInvitationEmail(context.Context, *SendInvitationEmailRequest) (*SendInvitationEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendInvitationEmail not implemented")
}
func (UnimplementedNotificationServiceServer) SendPasswordResetEmail(context.Context, *SendPasswordResetEmailRequest) (*SendPasswordResetEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPasswordResetEmail not implemented")
}
func (UnimplementedNotificationServiceServer) ScheduleTaskReminder(context.Context, *ScheduleTaskReminderRequest) (*ScheduleTaskReminderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleTaskReminder not implemented")
}
func (UnimplementedNotificationServiceServer) CancelTaskReminder(context.Context, *CancelTaskReminderRequest) (*CancelTaskReminderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTaskReminder not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SendVerificationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerificationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendVerificationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendVerificationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendVerificationEmail(ctx, req.(*SendVerificationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendInvitationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInvitationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendInvitationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendInvitationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendInvitationEmail(ctx, req.(*SendInvitationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendPasswordResetEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPasswordResetEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendPasswordResetEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendPasswordResetEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendPasswordResetEmail(ctx, req.(*SendPasswordResetEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_ScheduleTaskReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleTaskReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).ScheduleTaskReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_ScheduleTaskReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).ScheduleTaskReminder(ctx, req.(*ScheduleTaskReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CancelTaskReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CancelTaskReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CancelTaskReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CancelTaskReminder(ctx, req.(*CancelTaskReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVerificationEmail",
			Handler:    _NotificationService_SendVerificationEmail_Handler,
		},
		{
			MethodName: "SendInvitationEmail",
			Handler:    _NotificationService_SendInvitationEmail_Handler,
		},
		{
			MethodName: "SendPasswordResetEmail",
			Handler:    _NotificationService_SendPasswordResetEmail_Handler,
		},
		{
			MethodName: "ScheduleTaskReminder",
			Handler:    _NotificationService_ScheduleTaskReminder_Handler,
		},
		{
			MethodName: "CancelTaskReminder",
			Handler:    _NotificationService_CancelTaskReminder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/v1/notification.proto",
}
