// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: notification/v1/notification.proto

// 1. Tambahkan suffix versi (.v1) sesuai aturan Buf

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==========================================
// PAYLOAD: VERIFICATION
// ==========================================
type SendVerificationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationEmailRequest) Reset() {
	*x = SendVerificationEmailRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationEmailRequest) ProtoMessage() {}

func (x *SendVerificationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendVerificationEmailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendVerificationEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendVerificationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendVerificationEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SendVerificationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationEmailResponse) Reset() {
	*x = SendVerificationEmailResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationEmailResponse) ProtoMessage() {}

func (x *SendVerificationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendVerificationEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendVerificationEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendVerificationEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ==========================================
// PAYLOAD: INVITATION
// ==========================================
type SendInvitationEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProjectName   string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	TargetEmail   string                 `protobuf:"bytes,3,opt,name=target_email,json=targetEmail,proto3" json:"target_email,omitempty"`
	AcceptUrl     string                 `protobuf:"bytes,5,opt,name=accept_url,json=acceptUrl,proto3" json:"accept_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInvitationEmailRequest) Reset() {
	*x = SendInvitationEmailRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInvitationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInvitationEmailRequest) ProtoMessage() {}

func (x *SendInvitationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInvitationEmailRequest.ProtoReflect.Descriptor instead.
func (*SendInvitationEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendInvitationEmailRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *SendInvitationEmailRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *SendInvitationEmailRequest) GetTargetEmail() string {
	if x != nil {
		return x.TargetEmail
	}
	return ""
}

func (x *SendInvitationEmailRequest) GetAcceptUrl() string {
	if x != nil {
		return x.AcceptUrl
	}
	return ""
}

type SendInvitationEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInvitationEmailResponse) Reset() {
	*x = SendInvitationEmailResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInvitationEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInvitationEmailResponse) ProtoMessage() {}

func (x *SendInvitationEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInvitationEmailResponse.ProtoReflect.Descriptor instead.
func (*SendInvitationEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendInvitationEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendInvitationEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ==========================================
// PAYLOAD: PASSWORD RESET
// ==========================================
type SendPasswordResetEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Tautan lengkap yang dibangun Laravel, contoh: http://localhost:3000/password-reset/<token>?email=...
	ResetUrl      string `protobuf:"bytes,3,opt,name=reset_url,json=resetUrl,proto3" json:"reset_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetEmailRequest) Reset() {
	*x = SendPasswordResetEmailRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailRequest) ProtoMessage() {}

func (x *SendPasswordResetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailRequest.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendPasswordResetEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendPasswordResetEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendPasswordResetEmailRequest) GetResetUrl() string {
	if x != nil {
		return x.ResetUrl
	}
	return ""
}

type SendPasswordResetEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetEmailResponse) Reset() {
	*x = SendPasswordResetEmailResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetEmailResponse) ProtoMessage() {}

func (x *SendPasswordResetEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetEmailResponse.ProtoReflect.Descriptor instead.
func (*SendPasswordResetEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendPasswordResetEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendPasswordResetEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ==========================================
// PAYLOAD: REMINDER
// ==========================================
type ScheduleTaskReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskTitle     string                 `protobuf:"bytes,2,opt,name=task_title,json=taskTitle,proto3" json:"task_title,omitempty"`
	ProjectName   string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	AssigneeEmail string                 `protobuf:"bytes,4,opt,name=assignee_email,json=assigneeEmail,proto3" json:"assignee_email,omitempty"`
	// RFC3339 UTC, contoh: 2026-10-02T12:00:00Z
	DueDate       string `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskReminderRequest) Reset() {
	*x = ScheduleTaskReminderRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskReminderRequest) ProtoMessage() {}

func (x *ScheduleTaskReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskReminderRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskReminderRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleTaskReminderRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ScheduleTaskReminderRequest) GetTaskTitle() string {
	if x != nil {
		return x.TaskTitle
	}
	return ""
}

func (x *ScheduleTaskReminderRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ScheduleTaskReminderRequest) GetAssigneeEmail() string {
	if x != nil {
		return x.AssigneeEmail
	}
	return ""
}

func (x *ScheduleTaskReminderRequest) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

type ScheduleTaskReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleTaskReminderResponse) Reset() {
	*x = ScheduleTaskReminderResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleTaskReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskReminderResponse) ProtoMessage() {}

func (x *ScheduleTaskReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskReminderResponse.ProtoReflect.Descriptor instead.
func (*ScheduleTaskReminderResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *ScheduleTaskReminderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScheduleTaskReminderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelTaskReminderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReminderRequest) Reset() {
	*x = CancelTaskReminderRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskReminderRequest) ProtoMessage() {}

func (x *CancelTaskReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskReminderRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskReminderRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskReminderRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type CancelTaskReminderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReminderResponse) Reset() {
	*x = CancelTaskReminderResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskReminderResponse) ProtoMessage() {}

func (x *CancelTaskReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskReminderResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskReminderResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskReminderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskReminderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x0fnotification.v1\"w\n" +
	"\x1cSendVerificationEmailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"S\n" +
	"\x1dSendVerificationEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xad\x01\n" +
	"\x1aSendInvitationEmailRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x03R\tprojectId\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12!\n" +
	"\ftarget_email\x18\x03 \x01(\tR\vtargetEmail\x12\x1d\n" +
	"\n" +
	"accept_url\x18\x05 \x01(\tR\tacceptUrlJ\x04\b\x04\x10\x05R\x05token\"Q\n" +
	"\x1bSendInvitationEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"f\n" +
	"\x1dSendPasswordResetEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\treset_url\x18\x03 \x01(\tR\bresetUrl\"T\n" +
	"\x1eSendPasswordResetEmailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xba\x01\n" +
	"\x1bScheduleTaskReminderRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"task_title\x18\x02 \x01(\tR\ttaskTitle\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12%\n" +
	"\x0eassignee_email\x18\x04 \x01(\tR\rassigneeEmail\x12\x19\n" +
	"\bdue_date\x18\x05 \x01(\tR\adueDate\"R\n" +
	"\x1cScheduleTaskReminderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x19CancelTaskReminderRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"P\n" +
	"\x1aCancelTaskReminderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xde\x04\n" +
	"\x13NotificationService\x12v\n" +
	"\x15SendVerificationEmail\x12-.notification.v1.SendVerificationEmailRequest\x1a..notification.v1.SendVerificationEmailResponse\x12p\n" +
	"\x13SendInvitationEmail\x12+.notification.v1.SendInvitationEmailRequest\x1a,.notification.v1.SendInvitationEmailResponse\x12y\n" +
	"\x16SendPasswordResetEmail\x12..notification.v1.SendPasswordResetEmailRequest\x1a/.notification.v1.SendPasswordResetEmailResponse\x12s\n" +
	"\x14ScheduleTaskReminder\x12,.notification.v1.ScheduleTaskReminderRequest\x1a-.notification.v1.ScheduleTaskReminderResponse\x12m\n" +
	"\x12CancelTaskReminder\x12*.notification.v1.CancelTaskReminderRequest\x1a+.notification.v1.CancelTaskReminderResponseB/Z-go-notification-service/pb/notification/v1;v1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_notification_v1_notification_proto_goTypes = []any{
	(*SendVerificationEmailRequest)(nil),   // 0: notification.v1.SendVerificationEmailRequest
	(*SendVerificationEmailResponse)(nil),  // 1: notification.v1.SendVerificationEmailResponse
	(*SendInvitationEmailRequest)(nil),     // 2: notification.v1.SendInvitationEmailRequest
	(*SendInvitationEmailResponse)(nil),    // 3: notification.v1.SendInvitationEmailResponse
	(*SendPasswordResetEmailRequest)(nil),  // 4: notification.v1.SendPasswordResetEmailRequest
	(*SendPasswordResetEmailResponse)(nil), // 5: notification.v1.SendPasswordResetEmailResponse
	(*ScheduleTaskReminderRequest)(nil),    // 6: notification.v1.ScheduleTaskReminderRequest
	(*ScheduleTaskReminderResponse)(nil),   // 7: notification.v1.ScheduleTaskReminderResponse
	(*CancelTaskReminderRequest)(nil),      // 8: notification.v1.CancelTaskReminderRequest
	(*CancelTaskReminderResponse)(nil),     // 9: notification.v1.CancelTaskReminderResponse
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: notification.v1.NotificationService.SendVerificationEmail:input_type -> notification.v1.SendVerificationEmailRequest
	2, // 1: notification.v1.NotificationService.SendInvitationEmail:input_type -> notification.v1.SendInvitationEmailRequest
	4, // 2: notification.v1.NotificationService.SendPasswordResetEmail:input_type -> notification.v1.SendPasswordResetEmailRequest
	6, // 3: notification.v1.NotificationService.ScheduleTaskReminder:input_type -> notification.v1.ScheduleTaskReminderRequest
	8, // 4: notification.v1.NotificationService.CancelTaskReminder:input_type -> notification.v1.CancelTaskReminderRequest
	1, // 5: notification.v1.NotificationService.SendVerificationEmail:output_type -> notification.v1.SendVerificationEmailResponse
	3, // 6: notification.v1.NotificationService.SendInvitationEmail:output_type -> notification.v1.SendInvitationEmailResponse
	5, // 7: notification.v1.NotificationService.SendPasswordResetEmail:output_type -> notification.v1.SendPasswordResetEmailResponse
	7, // 8: notification.v1.NotificationService.ScheduleTaskReminder:output_type -> notification.v1.ScheduleTaskReminderResponse
	9, // 9: notification.v1.NotificationService.CancelTaskReminder:output_type -> notification.v1.CancelTaskReminderResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
